---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: demo
    image: gcr.io/devops-learn/demo:v1.0.0
    env:
    - name: DATABASE_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: DB_USERNAME
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: DB_PASSWORD