---
apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  containers:
  - name: app
    image: gcr.io/devops-learn/demo:v1.0.0
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: busybox:latest
    command: ["/bin/sh", "-c"]
    args: ["while true; do echo 'Hello from other side'; sleep 5; done"]