---
apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-rsync
spec:
  template:
    spec:
      volumes:
      - name: data-input
        gcePersistentDisk:
          pdName: glow-data-disk-200
          fsType: ext4
      containers:
      - name: demo
        image: gcr.io/mimetic-radio-405219/demo:v1.0.0
        command:
        - /bin/sh
        - -c
        - gsutil -m rsync -dr gs://glow-sportradar/data/input
        volumeMounts:
        - name: data-input
          mountPath: /data/input
      restartPolicy: Never
  backoffLimit: 0